[package]
authors.workspace = true
build = "build.rs"
description = "Kusama's BridgeHub parachain runtime"
edition.workspace = true
license.workspace = true
name = "bridge-hub-kusama-runtime"
repository.workspace = true
version.workspace = true

[build-dependencies]
substrate-wasm-builder = { optional = true , version = "13.0.0-dev" }

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hex-literal = { version = "0.4.1" }
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.188", optional = true, features = ["derive"] }
smallvec = "1.11.0"

# Substrate
frame-benchmarking = { default-features = false, optional = true, version = "24.0.0-dev" }
frame-executive = { default-features = false, version = "24.0.0-dev" }
frame-support = { default-features = false, version = "24.0.0-dev" }
frame-system = { default-features = false, version = "24.0.0-dev" }
frame-system-benchmarking = { default-features = false, optional = true, version = "24.0.0-dev" }
frame-system-rpc-runtime-api = { default-features = false, version = "22.0.0-dev" }
frame-try-runtime = { default-features = false, optional = true, version = "0.30.0-dev" }
pallet-aura = { default-features = false, version = "23.0.0-dev" }
pallet-authorship = { default-features = false, version = "24.0.0-dev" }
pallet-balances = { default-features = false, version = "24.0.0-dev" }
pallet-multisig = { default-features = false, version = "24.0.0-dev" }
pallet-session = { default-features = false, version = "24.0.0-dev" }
pallet-timestamp = { default-features = false, version = "23.0.0-dev" }
pallet-transaction-payment = { default-features = false, version = "24.0.0-dev" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = "24.0.0-dev" }
pallet-utility = { default-features = false, version = "24.0.0-dev" }
sp-api = { default-features = false, version = "22.0.0-dev" }
sp-block-builder = { default-features = false, version = "22.0.0-dev" }
sp-consensus-aura = { default-features = false, version = "0.28.0-dev" }
sp-core = { default-features = false, version = "24.0.0-dev" }
sp-inherents = { default-features = false, version = "22.0.0-dev" }
sp-io = { default-features = false, version = "26.0.0-dev" }
sp-offchain = { default-features = false, version = "22.0.0-dev" }
sp-runtime = { default-features = false, version = "27.0.0-dev" }
sp-session = { default-features = false, version = "23.0.0-dev" }
sp-std = { default-features = false, version = "11.0.0-dev" }
sp-storage = { default-features = false, version = "16.0.0-dev" }
sp-transaction-pool = { default-features = false, version = "22.0.0-dev" }
sp-version = { default-features = false, version = "25.0.0-dev" }

# Polkadot
kusama-runtime-constants = { path = "../../../relay/kusama/constants", default-features = false}
pallet-xcm = { default-features = false, version = "3.0.0-dev" }
pallet-xcm-benchmarks = { default-features = false, optional = true , version = "3.0.0-dev" }
polkadot-core-primitives = { default-features = false, version = "3.0.0-dev" }
polkadot-parachain-primitives = { default-features = false, version = "2.0.0-dev" }
polkadot-runtime-common = { default-features = false, version = "3.0.0-dev" }
xcm = { package = "staging-xcm", default-features = false, version = "3.0.0-dev" }
xcm-builder = { package = "staging-xcm-builder", default-features = false, version = "3.0.0-dev" }
xcm-executor = { package = "staging-xcm-executor", default-features = false, version = "3.0.0-dev" }

# Cumulus
cumulus-pallet-aura-ext = { default-features = false , version = "0.3.0-dev" }
cumulus-pallet-dmp-queue = { default-features = false , version = "0.3.0-dev" }
cumulus-pallet-parachain-system = { default-features = false, features = ["parameterized-consensus-hook",] , version = "0.3.0-dev" }
cumulus-pallet-session-benchmarking = { default-features = false, version = "5.0.0-dev" }
cumulus-pallet-xcm = { default-features = false , version = "0.3.0-dev" }
cumulus-pallet-xcmp-queue = { default-features = false , version = "0.3.0-dev" }
cumulus-primitives-core = { default-features = false , version = "0.3.0-dev" }
cumulus-primitives-utility = { default-features = false , version = "0.3.0-dev" }
pallet-collator-selection = { default-features = false , version = "5.0.0-dev" }
parachain-info = { package = "staging-parachain-info", default-features = false , version = "0.3.0-dev" }
parachains-common = { default-features = false , version = "3.0.0-dev" }

[dev-dependencies]
bridge-hub-test-utils = { version = "0.3.0-dev" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-session-benchmarking/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"frame-benchmarking?/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime?/std",
	"kusama-runtime-constants/std",
	"log/std",
	"pallet-aura/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-collator-selection/std",
	"pallet-multisig/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-utility/std",
	"pallet-xcm-benchmarks?/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"parachains-common/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain-primitives/std",
	"polkadot-runtime-common/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-session-benchmarking/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collator-selection/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-xcm-benchmarks/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]

try-runtime = [
	"cumulus-pallet-aura-ext/try-runtime",
	"cumulus-pallet-dmp-queue/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcm/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-collator-selection/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-session/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-xcm/try-runtime",
	"parachain-info/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"sp-runtime/try-runtime",
]

experimental = [ "pallet-aura/experimental" ]

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [ "sp-api/disable-logging" ]
