[package]
name = "asset-hub-polkadot-integration-tests"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Polkadot runtime integration tests with xcm-emulator"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.9" }

# Substrate
sp-runtime = { version = "31.0.1" }
frame-support = { version = "28.0.0" }
pallet-assets = { version = "29.0.0" }
pallet-balances = { version = "28.0.0" }
pallet-message-queue = { version = "31.0.0" }

# Polkadot
xcm = { package = "staging-xcm", version = "7.0.0" }
xcm-executor = { package = "staging-xcm-executor", default-features = false, version = "7.0.0" }
pallet-xcm = { version = "7.0.0" }

# Cumulus
parachains-common = { version = "7.0.0" }
xcm-emulator = { version = "0.5.0" }
asset-test-utils = { version = "7.0.1" }

# Local
emulated-chains = { path = "../../chains" }
integration-tests-common = { path = "../../common" }
asset-hub-polkadot-runtime = { path = "../../../../system-parachains/asset-hubs/asset-hub-polkadot" }
polkadot-runtime = { path = "../../../../relay/polkadot" }
system-parachains-constants = { path = "../../../../system-parachains/constants" }
