[package]
authors.workspace = true
build = "build.rs"
description = "Runtime of the Kusama Glutton System-Parachain"
edition.workspace = true
license.workspace = true
name = "glutton-kusama-runtime"
repository.workspace = true
version.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }

# Substrate
frame-benchmarking = { default-features = false, optional = true, version = "24.0.0-dev" }
frame-executive = { default-features = false, version = "24.0.0-dev" }
frame-support = { default-features = false, version = "24.0.0-dev" }
frame-system = { default-features = false, version = "24.0.0-dev" }
frame-system-rpc-runtime-api = { default-features = false, version = "22.0.0-dev" }
frame-system-benchmarking = { default-features = false, optional = true, version = "24.0.0-dev" }
frame-try-runtime = { default-features = false, optional = true, version = "0.30.0-dev" }
pallet-glutton = { default-features = false, optional = true, version = "10.0.0-dev" }
pallet-sudo = { default-features = false, optional = true, version = "24.0.0-dev" }
sp-api = { default-features = false, version = "22.0.0-dev" }
sp-block-builder = { default-features = false, version = "22.0.0-dev" }
sp-core = { default-features = false, version = "24.0.0-dev" }
sp-inherents = { default-features = false, version = "22.0.0-dev" }
sp-offchain = { default-features = false, version = "22.0.0-dev" }
sp-runtime = { default-features = false, version = "27.0.0-dev" }
sp-session = { default-features = false, version = "23.0.0-dev" }
sp-std = { default-features = false, version = "11.0.0-dev" }
sp-storage = { default-features = false, version = "16.0.0-dev" }
sp-transaction-pool = { default-features = false, version = "22.0.0-dev" }
sp-version = { default-features = false, version = "25.0.0-dev" }

# Polkadot
xcm = { package = "staging-xcm", default-features = false, version = "3.0.0-dev" }
xcm-builder = { package = "staging-xcm-builder", default-features = false, version = "3.0.0-dev" }
xcm-executor = { package = "staging-xcm-executor", default-features = false, version = "3.0.0-dev" }

# Cumulus
cumulus-pallet-parachain-system = { default-features = false, features = ["parameterized-consensus-hook",] , version = "0.3.0-dev" }
cumulus-pallet-xcm = { default-features = false , version = "0.3.0-dev" }
cumulus-primitives-core = { default-features = false , version = "0.3.0-dev" }
parachain-info = { package = "staging-parachain-info", default-features = false , version = "0.3.0-dev" }
parachains-common = { default-features = false , version = "3.0.0-dev" }

[build-dependencies]
substrate-wasm-builder = { version = "13.0.0-dev" }

[features]
default = [ "std" ]
runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-glutton/runtime-benchmarks",
	"pallet-sudo?/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
std = [
	"codec/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"frame-benchmarking?/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime?/std",
	"pallet-glutton/std",
	"pallet-sudo/std",
	"parachain-info/std",
	"parachains-common/std",
	"scale-info/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]
try-runtime = [
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcm/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-glutton/try-runtime",
	"pallet-sudo/try-runtime",
	"parachain-info/try-runtime",
	"sp-runtime/try-runtime",
]

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [ "sp-api/disable-logging" ]
