[package]
name = "polkadot-integration-tests-ahm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Polkadot integration tests for the Asset Hub Migration"
publish = false

[dev-dependencies]
codec = { workspace = true, default-features = true }
asset-hub-polkadot-runtime = { workspace = true, default-features = true, features = ["runtime-benchmarks"]}
authority-discovery-primitives = { workspace = true, default-features = true }
babe-primitives = { workspace = true, default-features = true }
beefy-primitives = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }
frame-benchmarking = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
frame-support = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
frame-system = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
grandpa = { workspace = true }
log = { workspace = true, default-features = true }
pallet-rc-migrator = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
pallet-ah-migrator = { workspace = true, features = ["std", "runtime-benchmarks"] }
pallet-balances = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
pallet-delegated-staking = { workspace = true, default-features = true, features = ["runtime-benchmarks"]}
pallet-indices = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
pallet-message-queue = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
pallet-timestamp = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
parachains-common = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
polkadot-parachain-primitives = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }
polkadot-runtime = { workspace = true, default-features = true, features = ["runtime-benchmarks"]}
polkadot-runtime-common = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
polkadot-runtime-constants = { workspace = true, default-features = true }
remote-externalities = { workspace = true }
runtime-parachains = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
sp-core = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-storage = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }
tokio = { features = ["full", "macros"], workspace = true }
xcm-builder = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
xcm-emulator = { workspace = true }
scale-info = { workspace = true, default-features = true }
pallet-proxy = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
sp-application-crypto = { workspace = true, default-features = true }
xcm = { workspace = true, default-features = true }
hex = { workspace = true }
pallet-whitelist = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
pallet-bounties = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
cumulus-pallet-parachain-system = { workspace = true, features = ["runtime-benchmarks"] }
pallet-xcm = { workspace = true, default-features = true, features = ["runtime-benchmarks"] }
system-parachains-common = { workspace = true, default-features = true, features = ["runtime-benchmarks"]}
kusama-runtime-constants = { workspace = true, default-features = true, features = ["runtime-benchmarks"]}
